In [7]:
# Aprendendo NumPy
# Biblioteca cientifca de números e tem boa performance com arrays dimensionaos
import numpy as np
new_array=np.array([1,2,3])
print(new_array)
# Mostrando uma posição do array
print(new_array[0])
print(new_array[1])

[1 2 3]
1
2


In [20]:
#
import time
import sys
b=range(1000)
print(sys.getsizeof(5)*len(b))
c = np.arange(1000)
print(c.size*c.itemsize)
size = 100000
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)
start = time.time()
result = [(x+y) for x,y in zip(L1, L2)]
print('python list took:' ,(time.time()-start)*1000)
#print(result)

28000
4000
python list took: 9.517431259155273


In [28]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.ndim)
print(a.itemsize)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
2
4
(3, 2)


In [21]:
start = time.time()
result = A1 + A2
print("Numpy array took:", (time.time()-start)*1000)

Numpy array took: 2.067089080810547


In [42]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(a)
print(a.itemsize)
print(a.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
8
(3, 2)


In [47]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.cdouble)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [50]:
print(np.zeros((3,4))) #-> Cria arrays com zeros
print(np.ones((2,5)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
l=range(5)
print(l)
np.arange(5)

range(0, 5)


array([0, 1, 2, 3, 4])

In [87]:
print('concatenate example:')
print(np.char.add(['hello','hi'], ['abc','xyz'])) #-> Concatena
print(np.char.center('Hello', 19,fillchar = '*')) #-> Completa os espaços de acordo com a quantidade
print(np.char.capitalize("hey ho let's go")) #-> Adiciona maiúsculo no inicio da frase
print(np.char.title('hey ho let\'s go')) #-> Deixa como titulo
print(np.char.lower("HELLO")) #-> Transforma tudo em minúsculo
print(np.char.upper('python is easy')) #-> Deixa tudo maiúsculo
print(np.char.split('Hello the new World')) #-> Faz os splits das palavras
print(np.char.strip(['Nina','admin','Anita'], 'a')) #-> Remove a letra
print(np.char.replace("He is a good dance", 'is', 'was'))

concatenate example:
['helloabc' 'hixyz']
*******Hello*******
Hey ho let's go
Hey Ho Let'S Go
hello
PYTHON IS EASY
['Hello', 'the', 'new', 'World']
['Nin' 'dmin' 'Anit']
He was a good dance
